package io.fiap.erp.exception;

public class UsuarioBloqueadoException extends RuntimeException{

    public UsuarioBloqueadoException(){}

    public UsuarioBloqueadoException(String message){}

    public UsuarioBloqueadoException(String message, Throwable cause){}

    public UsuarioBloqueadoException(Throwable cause){}

}
